### ISSUE TITLE
How to concat in local branch?

### ISSUE THREAD

**Issue by ZihaoH** [feymanpriv/DOLG-paddle#2]
Wonderful work!
But I got a question while reading the paper, since you didn't public the code. 
In the local branch, after the Multi-Atrous module, we will get 3 feature maps with a shape of Bx512xHxW. Then the lower branch will provide a “global” feature vector with Bx512x1x1. Till now, am I right?

Then, I wonder that if the concatenation operation is conducted on the channel dim or spatial dim?

**Comment by feymanpriv** [comment]
Hi, you can get answers from the code now.
